### ISSUE TITLE
Bad camera alignment or capture position?

### ISSUE THREAD

**Issue by theevl** [PolymerPrints/SnapmakerLightBurnHost#3]
Hi,

thanks for making this project/solution available.    (I like Lightburn very much).
I have a Snapmaker 2.0 A250 with the 10W laser, and LightBurn 1.0.04, in case that is important for troubleshooting.

At Step 5 in the usage, should it be "standard lens" or "fisheye lens"?
I have tried both, and the images look the same, but the scores are different.

When I capture an image, with DirectShow SoftCam, it appears that the camera is not seeing my entire buildplate (screenshot pasted below). 
The entire left edge is out of view (at least 10mm is missing).

It also seems that the camera is not "square"/parallel with the y-axis so the photo is slightly rotated.
There also seems to be a lot of "non-buildplate" in the camera image.

Is it possible to modify/adjust the position of the tool when it captures the image?

If capture position is not adjustable, can you provide guidance on where to place the calibration card?

Such as when Lightburn asks for "center" (image 1), should the card be placed in the middle of the buildplate 
or in the middle of the image-space?

(I do not know what I will do about the image for the upper right corner if I have to use the image-space as the frame of reference...  the Z-axis rail is in that space.)

![camera calibration offcenter](https://user-images.githubusercontent.com/12778936/211221234-a6c060a5-003c-48f1-82f9-7e5930c1c207.png)

Thanks for any assistance that you can provide.
Chris

**Comment by Maycuz** [comment]
Hi,

"Fisheye lens" should be used, as this will correct for the distortion that the wide-angle (fisheye) lens of the 10W module has. I do see some rotation in your image, but unfortunately I do not know how that can happen. Is it rotated in Luban as well?

The camera position issue is something I oddly overlooked when developing this application; I only took into account the A350. On your A250, this means the "base" coordinates cannot be reached or at the very least are not centered. 

To combat this I just released a new version that generates a config file: https://github.com/PolymerPrints/SnapmakerLightBurnHost/releases/tag/beta-config-file. You can start the application once and `config.json` will be generated. In there you can specify "base coordinates", i.e. the place where the camera takes a picture and where material thickness is measured.

```
{
    "basePositionX": 232.0,
    "basePositionY": 178.0,
    "basePositionZ": 290.0,
    "ipAddress": "192.168.333.89"
}
```

You will have to manually determine the correct capture position I'm afraid. If you do, it may be nice to share so that other A250 users can use it as a baseline.

Please give it a try and let me know if it fixes your issue!

**Comment by Maycuz** [comment]
Oops, did not mean to close...

**Comment by theevl** [comment]
Hi PolymerPrints!
Thanks for the fast fix!

I found that I could get all four corners of my buildplate in view using these coordinates for my A250:
{
    "basePositionX": 160.0,
    "basePositionY": 120.0,
    "basePositionZ": 175.0,
    "ipAddress": "0.0.0.0"
}

I am proceeding with the Camera alignment protocol now, to see if the rotation is something that can be fixed that way.
Now that I know that the position can be manipulated for the imaging, I would like to know the same for the laser-based thickness measurement function... but I will create a new thread for that. 

THANKS again!

Chris

**Comment by theevl** [comment]
FYI, i started using the Lightburn to control my A250 over the USB, and now something has gone screwy with my coordinates
my camera capture coordinates are no longer appropriate.

i will post again when I get it centered again (via lightburn)
thanks

**Comment by Maycuz** [comment]
I've had a similar issue before. Quoting myself (https://forum.snapmaker.com/t/working-camera-capture-with-lightburn/28397/30?u=mayco):

> What solved it for me was ensuring that the coordinate system was set to workspace coordinates. Before I start camera capture, I make sure to home (G28) and switch to workspace coordinates (G54). I have the same in my “End GCode” so that it’s guaranteed to be in workspace coordinates when the job is finished.

**Comment by Maycuz** [comment]
Hi @theevl, has this suggestion solved your issue?

**Comment by Maycuz** [comment]
Closing for now, please open a new ticket if the issue was not actually resolved yet!
